
FROM golang:1.15-alpine

# Making application directory
RUN mkdir -p /usr/src/app

# Setting application directory as working directory
WORKDIR /usr/src/app

# Copying code
COPY . /usr/src/app

# Starting service
CMD [ "go", "run", "cmd/main.go"]